### ISSUE TITLE
use Image input?

### ISSUE THREAD

**Issue by wwxFromTju** [village-people/flying-pig#1]
HI, all:
I think your work is insteresting, but I don't know, your model use the image input？or just use the feature vecotr？

best wish

maybe my English is bad, sorry about it.

**Comment by wwxFromTju** [comment]
nobody answer the question. so just close it

**Comment by floringogianu** [comment]
@wwxFromTju we are using the top-down symbolic view provided by the Malmo Platform, not the 3D perspective.

Similar to [PigChaseTopDownStateBuilder](https://github.com/village-people/flying-pig/blob/master/ai_challenge/pig_chase/environment.py#L75) we encoded a representation suitable to our CNN architecture: [PigChaseVillagePeopleBuilder18Binary](https://github.com/village-people/flying-pig/blob/master/ai_challenge/env/VillagePeopleBuilders.py#L80)
